export const products = [
  {
    id: 1,
    slug: 'smartclean-3x',
    name: 'SmartClean 3X',
    subtitle: 'Daily Laundry Detergent Sheets',
    price: 353,
    comparePrice: 441,
    discount: 20,
    rating: 4.9,
    reviews: 2847,
    badge: null,
    category: 'laundry',
    image: 'https://estrip.in/cdn/shop/files/pdp_s3.png?v=1783917395&width=480',
    images: [
      'https://estrip.in/cdn/shop/files/pdp_s3.png?v=1783917395&width=480',
      'https://estrip.in/cdn/shop/files/2_25.png?v=1783498480',
      'https://estrip.in/cdn/shop/files/pdp_s1_1.png?v=1783917607&width=480',
    ],
    desc: 'Daily laundry detergent sheets for regular clothes. Dissolves instantly in any temperature.',
    longDesc: 'SmartClean 3X is our flagship everyday laundry detergent sheet. Each 2g sheet is equivalent to 40g of standard liquid detergent — packing 20x the cleaning power in a fraction of the space. Plant-based enzymes break down tough Indian stains like dal, turmeric, and ghee, while our biodegradable PVA film dissolves completely without residue.',
    features: ['20x Super Concentrated', 'Works in cold & hot water', 'No plastic packaging', 'Hypoallergenic'],
    sheets: 30,
    scent: 'Fresh Cotton',
    subscription: true,
    subscriptionDiscount: 15,
    tags: ['bestseller', 'laundry'],
  },
  {
    id: 2,
    slug: 'proenzyme-5x',
    name: 'ProEnzyme 5X',
    subtitle: 'Heavy-Duty Stain Remover Sheets',
    price: 432,
    comparePrice: 540,
    discount: 20,
    rating: 4.8,
    reviews: 1923,
    badge: 'Best for Tough Stains',
    popular: true,
    category: 'laundry',
    image: 'https://estrip.in/cdn/shop/files/pdp_s2.png?v=1783917324&width=480',
    images: [
      'https://estrip.in/cdn/shop/files/pdp_s2.png?v=1783917324&width=480',
      'https://estrip.in/cdn/shop/files/2_25.png?v=1783498480',
    ],
    desc: 'Heavy-duty cleaning for sweat, oil, and tough stains. 5-enzyme blend tackles even set-in stains.',
    longDesc: 'ProEnzyme 5X features our advanced 5-enzyme blend — protease, amylase, lipase, cellulase, and mannanase — to break down every type of stain at the molecular level. Perfect for gym wear, workwear, and the toughest Indian cooking stains.',
    features: ['5-Enzyme Blend', 'Works on set-in stains', 'Safe for all fabrics', 'Cold water activated'],
    sheets: 30,
    scent: 'Sport Fresh',
    subscription: true,
    subscriptionDiscount: 15,
    tags: ['bestseller', 'laundry', 'tough-stains'],
  },
  {
    id: 3,
    slug: 'softtouch-baby',
    name: 'SoftTouch Baby',
    subtitle: 'Gentle Baby Laundry Sheets',
    price: 393,
    comparePrice: 491,
    discount: 20,
    rating: 4.9,
    reviews: 1456,
    badge: null,
    category: 'baby',
    image: 'https://estrip.in/cdn/shop/files/pdp_s1_1.png?v=1783917607&width=480',
    images: [
      'https://estrip.in/cdn/shop/files/pdp_s1_1.png?v=1783917607&width=480',
    ],
    desc: 'Gentle detergent sheets specifically for baby clothes. Dermatologist tested, 100% safe for newborn skin.',
    longDesc: 'SoftTouch Baby is formulated with the most sensitive skin in mind. Free from all harsh chemicals, optical brighteners, and synthetic fragrances. Our gentle plant-based formula is dermatologist tested and safe for newborns from day one.',
    features: ['Dermatologist tested', 'Fragrance-free option', 'No optical brighteners', 'Safe for newborns'],
    sheets: 30,
    scent: 'Fragrance-Free',
    subscription: true,
    subscriptionDiscount: 15,
    tags: ['baby', 'gentle'],
  },
  {
    id: 4,
    slug: 'floor-cleaner',
    name: 'Floor Cleaner Sheets',
    subtitle: 'Streak-Free Floor Cleaning Sheets',
    price: 399,
    comparePrice: 499,
    discount: 20,
    rating: 4.7,
    reviews: 892,
    badge: null,
    category: 'floor',
    image: 'https://estrip.in/cdn/shop/files/pdp_s5.png?v=1783917728&width=480',
    images: [
      'https://estrip.in/cdn/shop/files/pdp_s5.png?v=1783917728&width=480',
    ],
    desc: 'Streak-free cleaning on every floor. 1 sheet per bucket. Disinfects all hard surfaces.',
    longDesc: 'One sheet per bucket of water. That\'s all it takes. Our Floor Cleaner Sheets work on marble, tiles, wood, and all hard floors. The antibacterial formula kills 99.9% of bacteria while leaving a fresh, clean scent without any residue.',
    features: ['1 sheet = 1 bucket', 'Works on all floor types', '99.9% antibacterial', 'Streak-free formula'],
    sheets: 30,
    scent: 'Pine Fresh',
    subscription: true,
    subscriptionDiscount: 15,
    tags: ['floor', 'cleaning'],
  },
  {
    id: 5,
    slug: 'dishwashing-sheets',
    name: 'Dishwashing Sheets',
    subtitle: 'Grease-Cutting Dish Cleaning Sheets',
    price: 349,
    comparePrice: 436,
    discount: 20,
    rating: 4.8,
    reviews: 734,
    badge: null,
    category: 'dish',
    image: 'https://estrip.in/cdn/shop/files/pdp_s4.png?v=1783917481&width=480',
    images: [
      'https://estrip.in/cdn/shop/files/pdp_s4.png?v=1783917481&width=480',
    ],
    desc: 'Tough on grease, gentle on hands. 1 sheet equals 1 wash. Cleans every plate spotlessly.',
    longDesc: 'Our Dishwashing Sheets cut through oil and grease instantly. Gentle on hands with no harsh SLS, but powerful enough to cut through the toughest curried pans. One sheet per wash — just hold it under running water to activate.',
    features: ['Cuts through oil & grease', 'Gentle on hands', 'No SLS/SLES', '1 sheet per wash'],
    sheets: 30,
    scent: 'Lemon Zest',
    subscription: true,
    subscriptionDiscount: 15,
    tags: ['dish', 'kitchen'],
  },
  {
    id: 6,
    slug: 'stain-remover-spray',
    name: 'Stain Remover Spray',
    subtitle: 'Instant Stain Lift Spray',
    price: 299,
    comparePrice: 374,
    discount: 20,
    rating: 4.6,
    reviews: 421,
    badge: 'New Launch',
    category: 'laundry',
    image: 'https://estrip.in/cdn/shop/files/pdp_s6.png?v=1783917213&width=480',
    images: [
      'https://estrip.in/cdn/shop/files/pdp_s6.png?v=1783917213&width=480',
    ],
    desc: 'New Launch! Lifts fresh stains in seconds before they set. Works on food, wine, oil and more.',
    longDesc: 'Act fast on stains before they set. Our Stain Remover Spray uses an enzyme-activated formula to break down fresh stains in seconds. Works on food, wine, oil, ink, and more. Safe for all coloured fabrics.',
    features: ['Works in seconds', 'Pre-treat before washing', 'Safe for coloured fabrics', 'Enzyme-activated'],
    sheets: null,
    scent: 'Unscented',
    subscription: false,
    subscriptionDiscount: 0,
    tags: ['new', 'laundry', 'stain'],
  },
];

export const getProductBySlug = (slug) => products.find(p => p.slug === slug);
export const getProductsByCategory = (category) =>
  category === 'all' ? products : products.filter(p => p.category === category);
export const getFeaturedProducts = () => products.filter(p => p.popular || p.badge);
